### ISSUE TITLE
Homework 9 fixes

### ISSUE THREAD

**Issue by rtrana** [nickbratt16/TPSC#3]
Part I: 0.3/0.3

---

Part II: 0.3/0.3

---

Part III: 0/0.4
- [ ] Need to implement the entity relationship and modify the add functionality.

---

**Score**: 0.6/1.0

You can choose to fix the code or to keep the grade assigned in D2L. Once you complete and push your fixes to GitHub, be sure to close this issue. Closing this issue will notify me - no need to resubmit to D2L. Fixes need to be in before the last homework deadline.

**Comment by nickbratt16** [comment]
I finished setting up the many to many functionalities and also put in the delete option, but at the moment I don't need to use it so I just commented it out to save for a later date. I should be finished but please let me know if there is anything else.
Best, Nick
